version: '3.3'

services:
  webserver:
    build: .
    ports:
      - "9001:80"
    links:
      - mysql:mysql
    restart: always
    volumes:
      - ./html:/var/www/html/
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_USER: 'kmn400'
      MYSQL_PASSWORD: '1234'
      MYSQL_DATABASE: 'kmh'
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "52000:3306"

